from WebApp import my_login_manager

class Development_Config():
    SECRET_KEY = 'NEWWEBAPPLICATIONFINALPROJECT'
    SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:1234@localhost/studentproj'
    SQLALCHEMY_TRACK_MODIFICATIONS="False"
    STUDENT_SALT_KEY = "SECRETKEYTODECODEANDENCODESTUDENTDETAILSUSINGEMIALLINK"
    SUPERVISOR_SALT_KEY = "SECRETKEYTODECODEANDENCODESUPERVISORDETAILSUSINGEMIALLINK"
    FLASK_ADMIN_SWATCH = 'flatly'
    FLASK_ADMIN_CSS= 'Bootstrap_Overide.css'
    MAIL_SERVER='smtp.gmail.com'
    MAIL_PORT=465
    MAIL_USE_SSL=True
    MAIL_USERNAME='saikiri99@gmail.com'
    MAIL_PASSWORD='vihcgphpmspsntfx'
    DEFAULT_DEADLINE = "2023-04-26"
